-   name: install nginx
    hosts: all
    become: yes
    tasks:
        - name: update package repository
          yum:
            name: '*'
            state: latest
        - name: install nginx
          yum:
            name: nginx
            state: latest          
        - name: start nginx
          service:
            name: nginx
            state: started          
        - name: enabled nginx
          service:
            name: nginx
            enabled: yes
