-   name: install nginx
    hosts: all
    become: yes
    tasks:
        - name: update package repository
          yum:
            name: '*'
            state: latest
        - name: install nginx
          yum:
            name: nginx
            state: latest
        - name: Copy static files
          copy:
            src: "index.html"
            dest: "/usr/share/nginx/html/index.html"
            mode: 0644   
        - name: start nginx
          service:
            name: nginx
            state: started          
        - name: enabled nginx
          service:
            name: nginx
            enabled: yes
