-   name: install nginx
    hosts: all
    become: yes
    tasks:
        - name: update package repository
          yum:
            name: '*'
            state: latest
        - name: install nginx
          yum:
            name: nginx
            state: latest
        - name: start nginx
          service:
            name: nginx
            state: started          
        - name: enabled nginx
          service:
            name: nginx
            enabled: yes
        - name: chmod for /usr/share/nginx/html/
          file:
            path: /usr/share/nginx/html/
            state: directory
            mode: '777'
            recurse: yes
        - name: copy index.html
          copy:
            src: index.html
            dest: /usr/share/nginx/html/index.html
