-   name: install nginx
    hosts: all
    become: yes
    tasks:
        - name: install git        
          yum:
            name: git
            state: present    
        - name: Git checkout
          git:
            repo: 'https://github.com/dev-sec/ansible-collection-hardening.git'
            dest: /srv/checkout
        - name: ls
          command: ls /srv/checkout
        - name: pwd
          command: pwd           
        - include: /srv/checkout/ansible-collection-hardening/roles/os_hardening/defaults/main.yml           
        - name: update package repository
          yum:
            name: '*'
            state: latest
        - name: install epel package 
          command: amazon-linux-extras install epel -y
        - name: install nginx        
          yum:
            name: nginx
            state: present
        - name: start nginx
          service:
            name: nginx
            state: started          
        - name: enabled nginx
          service:
            name: nginx
            enabled: yes
        - name: chmod for /usr/share/nginx/html/
          file:
            path: /usr/share/nginx/html/
            state: directory
            mode: '777'
            recurse: yes
        - name: copy index.html
          copy:
            src: index.html
            dest: /usr/share/nginx/html/index.html        
